<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;
use MailForm\Collection\FormTypeCollection;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('MailForm:Admin:Form@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new form'); ?></a></li>
		 <li><a href="<?php echo $this->url('MailForm:Admin:Form@addAjaxAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new AJAX form'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

		 <?php if (!empty($forms)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('MailForm:Admin:Form@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('MailForm:Admin:Form@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<h4 class="inline"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Mail forms'); ?></h4>

<form>
	<div class="table-responsive">
		<table class="table table-hover table-bordered table-striped">
			<thead>
				<tr>
					<th class="text-center">
						<?php if (!empty($forms)): ?>
						<input type="checkbox" />
						<?php endif; ?>
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Type'); ?></th>
					<th class="text-center"><?php $this->show('SEO'); ?></th>
					<th class="text-center"><?php $this->show('Field count'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>

            <?php if (!empty($forms)): ?>
            <tbody>
                <?php foreach ($forms as $form): ?>
				<tr>
					<td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $form->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $form->getId(); ?></td>
					<td class="text-center"><?php echo $form->getName(); ?></td>
					<td class="text-center">
                        <?php $this->show((new FormTypeCollection)->findByKey($form->getType())); ?>
                    </td>
					<td class="text-center">
                        <?php echo Element::checkbox(sprintf('seo[%s]', $form->getId()), $form->getSeo()); ?>
					</td>
					<td class="text-center"><?php echo $form->getFieldCount(); ?></td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this page on site'); ?>" data-button="view" target="_blank" href="<?php echo $form->getUrl(); ?>"><i class="glyphicon glyphicon-search"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this page'); ?>" data-button="edit" href="<?php echo $this->url('MailForm:Admin:Form@editAction', $form->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this page'); ?>" data-button="delete" data-url="<?php echo $this->url('MailForm:Admin:Form@deleteAction', $form->getId()); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>
		
		<?php if (empty($forms)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No forms'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
