<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\HtmlHelper;
use Krystal\Form\Element;

?>

<form data-group="form">
	
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Form'); ?></a></li>
		<li role="presentation"><a href="#menu" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-list"></i> <?php $this->show('Item in menu'); ?></a></li>
	</ul>
	
	<div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
			<div class="well">
				
                <?php echo Element::hidden('form[id]', $form->getId()); ?>
                <?php echo Element::hidden('form[web_page_id]', $form->getWebPageId()); ?>
                <?php echo Element::hidden('web_page_id', $form->getWebPageId()); ?>
                
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::text('form[name]', $form->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Page name'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>

				<div class="form-group clearfix <?php HtmlHelper::addOnDemand(!$extendedMode, 'hidden'); ?>">
					<label class="col-lg-2 control-label"><?php $this->show('Template'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::text('form[template]', $form->getTemplate(), array('class' => 'form-control', 'placeholder' => $this->translate('Framework-compliant template file inside current site theme directory'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix <?php HtmlHelper::addOnDemand(!$extendedMode, 'hidden'); ?>">
					<label class="col-lg-2 control-label"><?php $this->show('Message view'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::text('form[message_view]', $form->getMessageView(), array('class' => 'form-control', 'placeholder' => $this->translate('Framework-compliant template file for the email message to be sent'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<?php echo Element::textarea('form[description]', $form->getDescription(), array('data-wysiwyg' => 'true')); ?>
					</div>
				</div>
				
				<div class="options">
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
						<div class="col-lg-10">
                            <?php echo Element::checkbox('form[seo]', $form->getSeo(), array('class' => 'form-control')); ?>
						</div>
					</div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
                                <?php echo Element::text('form[slug]', $form->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this page. By default is taken from the name'))); ?>
								<span class="input-group-addon">
									<a href="#" data-button="slug">
										<i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i>
									</a>
								</span>
							</div>
						</div>
					</div>

                    <div class="form-group clearfix">
                        <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?php echo Element::text('form[title]', $form->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Page title'))); ?>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                            </div>
                        </div>
                    </div>
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
						<div class="col-lg-10">
							<div class="input-group">
                                <?php echo Element::text('form[keywords]', $form->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
								<span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
							</div>
						</div>
					</div>
					
					
					<div class="form-group clearfix">
						<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
						<div class="col-lg-10">
                            <?php echo Element::textarea('form[meta_description]', $form->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
						</div>
					</div>
				</div>
			</div>
			
			<?php if (!$form->getId()): ?>
			
			<button data-button="add" data-back-url="<?php echo $this->url('MailForm:Admin:Form@editAction', null); ?>" data-url="<?php echo $this->url('MailForm:Admin:Form@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
			<button data-button="add-create" data-url="<?php echo $this->url('MailForm:Admin:Form@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
			
			<?php else: ?>
			
			<button data-button="save" data-url="<?php echo $this->url('MailForm:Admin:Form@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
			<button data-button="save-create" data-back-url="<?php echo $this->url('MailForm:Admin:Form@addAction'); ?>" data-url="<?php echo $this->url('MailForm:Admin:Form@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
			
			<?php endif; ?>
			
			<button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
			<button data-button="cancel" data-url="<?php echo $this->url('MailForm:Admin:Form@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
			
		</div>
		
		<div class="tab-pane fade" id="menu" role="tabpanel">
			<?php $this->loadBlock('menu-widget'); ?>
		</div>
	</div>
</form>
