<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\Service\LanguageManager;
use Cms\View\Icon;
use MailForm\Collection\FieldTypeCollection;

?>

<form class="card" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item">
            <a class="nav-link active" href="#page" role="tab" data-bs-toggle="tab">
                <i class="fas fa-envelope-open-text"></i> <?= $this->translate('Form'); ?>
            </a>
        </li>
        <li role="presentation" class="nav-item">
            <a class="nav-link" href="#message" role="tab" data-bs-toggle="tab">
                <i class="fas fa-grip-horizontal"></i> <?= $this->translate('Configuration'); ?>
            </a>
        </li>
        <?php if (!$new): ?>
        <li role="presentation" class="nav-item">
            <a class="nav-link" href="#fields" role="tab" data-bs-toggle="tab">
                <i class="fas fa-clipboard-list"></i> <?= $this->translate('Form fields'); ?> <small class="text-muted">(<?= count($extraFields); ?>)</small>
            </a>
        </li>
        <?php $this->loadPartialIfPossible('block-tab'); ?>
        <?php endif; ?>
    </ul>

    <div class="tab-content pt-3">
        <div class="tab-pane fade show active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <?php $entity = LanguageManager::findByLangId($language->getId(), $form); ?>

                <div class="tab-pane fade <?= $index == 0 ? 'show active' : null; ?>" id="<?= sprintf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Page name')]); ?>
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Flash message'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][flash]', $language->getId()), $entity->getFlash(), ['class' => 'form-control', 'placeholder' => $this->translate('Flash message after form submission. If empty, default is used')]); ?>
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Public offer before submission'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][terms]', $language->getId()), $entity->getTerms(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <?php if ($entity->isRegularForm()): ?>
                    <div class="options">
                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), ['class' => 'form-control', 'placeholder' => $this->translate('URL slug for this page. By default its taken from the name')]); ?>
                                    <span class="input-group-text" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>">
                                        <a href="#"><i class="bi bi-arrow-clockwise" data-bs-toggle="tooltip" title="<?= $this->translate('Refresh the slug'); ?>"></i></a>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Change frequency'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), ['class' => 'form-select']); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Priority'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), ['class' => 'form-select']); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), ['class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Page title')]); ?>
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), ['class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines')]); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), ['class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines')]); ?>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>

                </div>
                <?php endforeach; ?>
            </div>

            <?php $this->loadPartial('actions', [
                'new' => $new,
                'add' => sprintf('MailForm:Admin:Form@%s', $entity->isRegularForm() ? 'addAction' : 'addAjaxAction'),
                'edit' => 'MailForm:Admin:Form@editAction',
                'save' => 'MailForm:Admin:Form@saveAction',
                'cancel' => 'MailForm:Admin:Form@gridAction',
                'options' => $entity->isRegularForm()
            ]); ?>
        </div>

        <div class="tab-pane fade" id="message" role="tabpanel">
            <?= Element::hidden('form[id]', $entity->getId()); ?>
            <?= Element::hidden('form[type]', $entity->getType()); ?>

            <?php $this->loadPartialIfPossible('block-field'); ?>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Template'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('form[template]', $entity->getTemplate(), ['class' => 'form-control', 'placeholder' => $this->translate('Framework-compliant template file')]); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Flash message position'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('form[flash_position]', $this->translateArray($flashPositions), $entity->getFlashPosition(), ['class' => 'form-select']); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Enable labels'); ?></label>
                <div class="col-lg-10">
                    <div class="form-check">
                        <?= Element::checkbox('form[labeled]', $entity->getLabeled(), ['class' => 'form-check-input']); ?>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Enable CAPTCHA'); ?></label>
                <div class="col-lg-10">
                    <div class="form-check">
                        <?= Element::checkbox('form[captcha]', $entity->getCaptcha(), ['class' => 'form-check-input']); ?>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Enable auto complete on site'); ?></label>
                <div class="col-lg-10">
                    <div class="form-check">
                        <?= Element::checkbox('form[autocomplete]', $entity->getAutocomplete(), ['class' => 'form-check-input']); ?>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Enable SEO'); ?></label>
                <div class="col-lg-10">
                    <div class="form-check">
                        <?= Element::checkbox('form[seo]', $entity->getSeo(), ['class' => 'form-check-input']); ?>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Subject'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('form[subject]', $entity->getSubject(), ['class' => 'form-control', 'placeholder' => $this->translate('Message subject')]); ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="row">
                    <div class="col-lg-8">
                        <?= Element::textarea('form[message]', $entity->getMessage(), ['id' => 'message-input', 'rows' => '13', 'class' => 'form-control', 'placeholder' => $this->translate('Target message')]); ?>

                        <?php if ($entity->getId()): ?>
                        <div class="mt-3">
                            <button data-button="generate" data-output="#message-input" data-url="<?= $this->url('MailForm:Admin:Form@messageAction', $entity->getId()); ?>" class="btn btn-primary">
                                <i class="bi bi-envelope"></i> <?= $this->translate('Generate message'); ?>
                            </button>
                        </div>
                        <?php endif; ?>
                    </div>
                    
                    <div class="col-lg-4">
                        <div class="alert alert-danger">
                            <?php if (!empty($subjectVars)): ?>
                            <p><?= $this->translate('You can use the following subject variables'); ?>: </p>
                            <br />
                            <ul class="list-unstyled">
                                <?php foreach ($subjectVars as $subjectVar => $varName): ?>
                                <li>
                                    <span class="badge bg-light border" style="cursor: pointer;" data-bs-toggle="tooltip" data-bs-placement="left" title="<?= $this->translate('Click to copy'); ?>" data-button="clipboard" data-value="<?= $subjectVar; ?>">
                                        <?= $subjectVar; ?>
                                    </span> 
                                    <small>- <?= $varName; ?></small>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php else: ?>
                            <p><?= $this->translate('There must be at lease one text field created to make use of variables in the subject'); ?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="fields" role="tabpanel">
            <div class="row py-4">
                <div class="col-lg-6">
                    <h3><i class="bi bi-list-task"></i> <?= $this->translate('Form fields'); ?> <small>(<?= count($extraFields); ?>)</small></h3>
                </div>

                <div class="col-lg-6 text-lg-end">
                    <a class="btn btn-primary" href="<?= $this->url('MailForm:Admin:Field@addAction', $entity->getId()); ?>">
                        <?= $this->translate('Add new field'); ?>
                    </a>
                </div>
            </div>

            <?= $this->widget(new GridViewWidget($extraFields, [
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],
                    [
                        'column' => 'name',
                        'attributes' => ['class' => null]
                    ],
                    [
                        'column' => 'type',
                        'translateable' => true,
                        'value' => function($row){
                            $typeCol = new FieldTypeCollection();
                            return $typeCol->findByKey($row['type']);
                        }
                    ],
                    
                    [
                        'column' => 'order',
                    ],

                    [
                        'column' => 'required',
                        'label' => 'Required to be filled in',
                        'translateable' => true,
                        'value' => function($entity) {
                            return $entity->getRequired() ? 'Yes' : 'No';
                        }
                    ],

                    [
                        'column' => 'row'
                    ]
                ],
                'actions' => [
                    function($row){
                        return Icon::edit(
                            $this->url('MailForm:Admin:Field@editAction', $row['id']),
                            $this->translate('Edit this field')
                        );
                    },
                    function($row){
                        return Icon::remove(
                            $this->url('MailForm:Admin:Field@deleteAction', $row['id']),
                            $this->translate('Remove this field')
                        );
                    }
                ]
            ])); ?>
        </div>

        <?php $this->loadPartialIfPossible('block-content'); ?>
    </div>
</form>