<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use MailForm\Collection\FormTypeCollection;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('MailForm:Admin:Form@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new form'); ?></a></li>
		 <li><a href="<?php echo $this->url('MailForm:Admin:Form@addAjaxAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new AJAX form'); ?></a></li>
		 <li><a href="<?php echo $this->url('MailForm:Admin:SubmitLog@indexAction'); ?>"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('Submit logs'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

		 <?php if (!empty($forms)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('MailForm:Admin:Form@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('MailForm:Admin:Form@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<h4 class="inline"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Mail forms'); ?></h4>

<form autocomplete="off">
	<div class="table-responsive">
        <?= $this->widget(new GridViewWidget($forms, array(
            // A column to be considered as a primary key
            'pk' => 'id',
            'batch' => true,
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'type',
                    'translateable' => true,
                    'value' => function($row){
                        $typeCol = new FormTypeCollection();
                        return $typeCol->findByKey($row['type']);
                    }
                ),

                array(
                    'column' => 'seo',
                    'label' => 'SEO',
                    'value' => function($form){
                        if ($form->isRegularForm()) {
                            return Element::checkbox(sprintf('seo[%s]', $form->getId()), $form->getSeo());
                        } else {
                            return null;
                        }
                    }
                ),

                array(
                    'column' => 'field_count',
                    'label' => 'Field count'
                )
            ),

            'actions' => array(
                'view' => function($form){
                    if ($form->isRegularForm()) {
                        return Icon::view($form->getUrl(), $this->translate('View this page on site'));
                    } else {
                        return null;
                    }
                },

                'edit' => function($form){
                    return Icon::edit(
                        $this->url('MailForm:Admin:Form@editAction', $form->getId()),
                        $this->translate('Edit this page')
                    );
                },

                'remove' => function($form){
                    return Icon::remove(
                        $this->url('MailForm:Admin:Form@deleteAction', $form->getId()),
                        $this->translate('Remove this page')
                    );
                }
            )
        ))); ?>    

        <?php if (empty($forms)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No forms'); ?></h2>
        </div>
        <?php endif; ?>
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
