<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use MailForm\Collection\FormTypeCollection;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <div class="btn-toolbar">
        <div class="dropdown">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
          </button>

          <div class="dropdown-menu">
             <a class="dropdown-item" href="<?php echo $this->url('MailForm:Admin:Form@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new form'); ?></a>
             <a class="dropdown-item" href="<?php echo $this->url('MailForm:Admin:Form@addAjaxAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new AJAX form'); ?></a>
             <a class="dropdown-item" href="<?php echo $this->url('MailForm:Admin:SubmitLog@indexAction'); ?>"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('Submit logs'); ?></a>
             <div class="dropdown-divider"></div>
             <div class="dropdown-header"><?php $this->show('Actions'); ?></div>

             <?php if (!empty($forms)): ?>
             <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?php echo $this->url('MailForm:Admin:Form@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a>
             <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('MailForm:Admin:Form@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
             <?php else: ?>
             <a class="dropdown-item disabled"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a>
             <a class="dropdown-item disabled"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
             <?php endif; ?>
          </div>
        </div>
    </div>

    <h4 class="inline"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Mail forms'); ?></h4>

    <form autocomplete="off">
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($forms, array(
                // A column to be considered as a primary key
                'pk' => 'id',
                'batch' => true,
                'tableClass' => 'table table-hover table-bordered table-striped table-sm',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'type',
                        'translateable' => true,
                        'value' => function($row){
                            $typeCol = new FormTypeCollection();
                            return $typeCol->findByKey($row['type']);
                        }
                    ),

                    array(
                        'column' => 'seo',
                        'label' => 'SEO',
                        'value' => function($form){
                            if ($form->isRegularForm()) {
                                return Element::checkbox(sprintf('seo[%s]', $form->getId()), $form->getSeo());
                            } else {
                                return null;
                            }
                        }
                    ),

                    array(
                        'column' => 'field_count',
                        'label' => 'Field count'
                    )
                ),

                'actions' => array(
                    'view' => function($form){
                        if ($form->isRegularForm()) {
                            return Icon::view($form->getUrl(), $this->translate('View this page on site'));
                        } else {
                            return null;
                        }
                    },

                    'edit' => function($form){
                        return Icon::edit(
                            $this->url('MailForm:Admin:Form@editAction', $form->getId()),
                            $this->translate('Edit this page')
                        );
                    },

                    'remove' => function($form){
                        return Icon::remove(
                            $this->url('MailForm:Admin:Form@deleteAction', $form->getId()),
                            $this->translate('Remove this page')
                        );
                    }
                )
            ))); ?>    

            <?php if (empty($forms)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No forms'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>
