<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;

defined('KRYSTAL') or die;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('Submission logs'); ?> <small>(<?= count($logs); ?>)</small></h2>

<div class="table-responsive">
    <?= Grid::render($logs, array(
        // A column to be considered as a primary key
        'pk' => 'id',
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'datetime',
                'label' => 'Date and time'
            ),

            array(
                'column' => 'subject'
            ),

            array(
                'column' => 'attachments',
                'label' => 'Attachments file count',
                'value' => function($entity){
                    if ($entity->getAttachments() == 0) {
                        return '-';
                    } else {
                        return $entity->getAttachments();
                    }
                }
            )
        ),

        'actions' => array(
            'view' => function($form){
                return Element::icon('glyphicon glyphicon-eye-open', $this->url('MailForm:Admin:SubmitLog@viewAction', $form->getId()), array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('View this message'), 'data-button' => 'ajax-view'));
            },

            'remove' => function($row){
                return Element::icon('glyphicon glyphicon-remove', '#', array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Remove this log'), 'data-button' => 'delete', 'data-url' => $this->url('MailForm:Admin:SubmitLog@deleteAction', $row['id'])));
            }
        )

    ), $this->translator); ?>    

    <?php if (empty($logs)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No logs'); ?></h2>
    </div>
    <?php endif; ?>
</div>