<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<?php if (!empty($logs)): ?>
<div class="btn-toolbar mb-3">
    <a data-button="delete" data-message="<?php $this->show('Do you really want to clear all message logs?'); ?>" class="btn btn-primary" href="<?= $this->url('MailForm:Admin:SubmitLog@clearAction'); ?>"><?php $this->show('Clear all'); ?></a>
</div>
<?php endif; ?>

<div class="card">
    <?php $this->loadPartial('card-header', [
        'title' => 'Submission logs',
        'rows' => $logs
    ]); ?>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($logs, [
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'datetime',
                    'label' => 'Date and time'
                ],

                [
                    'column' => 'subject'
                ],

                [
                    'column' => 'attachments',
                    'label' => 'Attachments file count',
                    'value' => function($entity){
                        if ($entity->getAttachments() == 0) {
                            return '-';
                        } else {
                            return $entity->getAttachments();
                        }
                    }
                ]
            ],

            'actions' => [
                'view' => function($form){
                    return Icon::details(
                        $this->url('MailForm:Admin:SubmitLog@viewAction', $form->getId()), 
                        $this->translate('View this message'),
                        ['data-button' => 'ajax-view']
                    );
                },

                'remove' => function($form){
                    return Icon::remove(
                        $this->url('MailForm:Admin:SubmitLog@deleteAction', $form->getId()),
                        $this->translate('Remove this log')
                    );
                }
            ]
        ])); ?>

        <?php if (empty($logs)): ?>
        <div class="d-flex justify-content-center my-5">
            <div class="text-center text-muted">
                <h2><i class="bi bi-x-circle"></i> <?php $this->show('No logs'); ?></h2>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>