<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<?php if (!empty($logs)): ?>
<div class="btn-toolbar">
    <a data-button="delete" data-message="<?php $this->show('Do you really want to clear all message logs?'); ?>" class="btn btn-primary" href="<?= $this->url('MailForm:Admin:SubmitLog@clearAction'); ?>"><?php $this->show('Clear all'); ?></a>
</div>
<?php endif; ?>

<div class="card">
    <?php $this->loadPartial('card-header', array(
        'title' => 'Submission logs',
        'rows' => $logs
    )); ?>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($logs, array(
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'datetime',
                    'label' => 'Date and time'
                ),

                array(
                    'column' => 'subject'
                ),

                array(
                    'column' => 'attachments',
                    'label' => 'Attachments file count',
                    'value' => function($entity){
                        if ($entity->getAttachments() == 0) {
                            return '-';
                        } else {
                            return $entity->getAttachments();
                        }
                    }
                )
            ),

            'actions' => array(
                'view' => function($form){
                    return Icon::details(
                        $this->url('MailForm:Admin:SubmitLog@viewAction', $form->getId()), 
                        $this->translate('View this message'),
                        array('data-button' => 'ajax-view')
                    );
                },

                'remove' => function($form){
                    return Icon::remove(
                        $this->url('MailForm:Admin:SubmitLog@deleteAction', $form->getId()),
                        $this->translate('Remove this log')
                    );
                }
            )
        ))); ?>

        <?php if (empty($logs)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No logs'); ?></h2>
        </div>
        <?php endif; ?>
    </div>
</div>