<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="value" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item">
            <a class="nav-link active" href="#value" role="tab" data-toggle="tab">
                <i class="fas fa-align-left"></i> <?php $this->show('Value'); ?>
            </a>
        </li>

        <li role="presentation" class="nav-item">
            <a class="nav-link" href="#configuration" role="tab" data-toggle="tab">
                <i class="fas fa-grip-horizontal"></i> <?php $this->show('Configuration'); ?>
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="value" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade <?= $index == 0 ? 'show active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $value); ?>

                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"><?php $this->show('Value'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::textarea(sprintf('translation[%s][value]', $language->getId()), $entity->getValue(), ['class' => 'form-control', 'placeholder' => $this->translate('Name')]); ?>
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php if ($entity->isCheckboxList()): ?>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"><?php $this->show('Default'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::select(sprintf('translation[%s][default]', $language->getId()), $this->translateArray($states), $entity->getDefault(), ['class' => 'form-control']); ?>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="tab-pane fade" id="configuration" role="tabpanel">
            <?= Element::hidden('value[id]', $entity->getId()); ?>
            <?= Element::hidden('value[field_id]', $entity->getFieldId()); ?>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?php $this->show('Order'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('value[order]', $entity->getOrder(), ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => $new,
        'add' => $this->createQueryUrl('MailForm:Admin:FieldValue@addAction', ['form_id' => $entity->getFormId(), 'field_id' => $entity->getFieldId()]),
        'edit' => 'MailForm:Admin:FieldValue@editAction',
        'save' => 'MailForm:Admin:FieldValue@saveAction',
        'cancel' => ['MailForm:Admin:Field@editAction', $entity->getFieldId()],
    ]); ?>
    
</form>