<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form data-group="value">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#value" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Value'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="value" role="tabpanel">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $value); ?>

                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Value'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::textarea(sprintf('translation[%s][value]', $language->getId()), $entity->getValue(), array('class' => 'form-control', 'placeholder' => $this->translate('Name'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="configuration" role="tabpanel">
            <div class="well">
                <?php echo Element::hidden('value[id]', $entity->getId()); ?>
                <?php echo Element::hidden('value[field_id]', $entity->getFieldId()); ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('value[order]', $entity->getOrder(), array('class' => 'form-control')); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if ($new): ?>
	<button data-button="add" data-back-url="<?php echo $this->url('MailForm:Admin:FieldValue@editAction', null); ?>" data-url="<?php echo $this->url('MailForm:Admin:FieldValue@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('MailForm:Admin:FieldValue@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

    <?php else: ?>
	<button data-button="save" data-url="<?php echo $this->url('MailForm:Admin:FieldValue@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('MailForm:Admin:FieldValue@addAction'); ?>" data-url="<?php echo $this->url('MailForm:Admin:FieldValue@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
	<?php endif; ?>

    <button data-button="cancel" data-url="<?php echo $this->url('MailForm:Admin:FieldValue@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
