<?php if ($flashBag->has('success')): ?>
<div class="alert alert-dismissible fade show alert-success">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <?= $this->translate($flashBag->get('success')); ?>
</div>
<?php endif; ?>

<?php if ($flashBag->has('warning')): ?>
<div class="alert alert-dismissible fade show alert-warning">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <?= $this->translate($flashBag->get('warning')); ?>
</div>
<?php endif; ?>