<?php

/**
 * This partial template field defines how a single field 
 * is being rendered. This file gets included inside foreach on each iteration
 */

use Krystal\Form\Element;
use Krystal\Stdlib\ArrayUtils;

// Defaults
$name = sprintf('field[%s]', $field->getId());
$attrs = [
    'class' => 'form-control', 
    'id' => $field->getId(), 
    'placeholder' => $field->getHint()
];
$default = $field->getDefault();

?>

<div class="form-group mb-4">
    <?php if ($field->isHidden()): ?>
        <?= Element::hidden($name, $default); ?>
    <?php else: ?>

    <?php if ($field->getName()): ?>
        <label for="<?= $field->getId(); ?>" class="form-label"><?= $field->getName(); ?></label>
    <?php endif; ?>

    <?php if ($field->isFile()): ?>
        <?= Element::file($name, null, ['class' => 'form-control', 'id' => $field->getId(), 'title' => $field->getHint(), 'accept' => $field->getExtensionHints()]); ?>
    <?php endif; ?>

    <?php if ($field->isText()): ?>
        <?= Element::text($name, $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isPassword()): ?>
        <?= Element::password($name, $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isNumber()): ?>
        <?= Element::number($name, $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isEmail()): ?>
        <?= Element::email($name, $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isDate()): ?>
        <?= Element::date($name, $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isDatetime()): ?>
        <?= Element::date($name, $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isTextarea()): ?>
        <?= Element::textarea($name, $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isSelect()): ?>
        <?= Element::select($name, $field->getValuesList(), $default, $attrs); ?>
    <?php endif; ?>

    <?php if ($field->isBoolean()): ?>
        <div class="form-check">
            <?= Element::checkbox($name, (bool) $default, ['id' => $field->getId(), 'title' => $field->getHint(), 'class' => 'form-check-input']); ?>
        </div>
    <?php endif; ?>

    <?php if ($field->isCheckboxList()): ?>
        <?php foreach ($field->getValues() as $value): ?>
        <div class="form-check">
            <?= Element::checkbox($name.'[]', $value->isChecked(), ['value' => $value->getValue(), 'class' => 'form-check-input'], false); ?>
            <label class="form-check-label">
                <?= $value->getValue(); ?>
            </label>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($field->isRadioList()): ?>
        <?php foreach ($field->getValues() as $value): ?>
        <div class="form-check">
            <?= Element::radio($name, $value->getValue(), $default, ['class' => 'form-check-input']); ?>
            <label class="form-check-label">
                <?= $value->getValue(); ?>
            </label>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php endif; ?>
</div>