<?php

/**
 * The form itself to be included in site templates
 */

use Krystal\Form\Element;
use MailForm\Service\FieldService;
use MailForm\Collection\FlashPositionCollection;

$fields = $page->getDynamicFields();

// View configuration parameters
$resetButton = isset($resetButton) && $resetButton == true;
$resetButtonText = isset($resetButtonText) ? $resetButtonText : 'Reset';
$submitButtonText = isset($submitButtonText) ? $submitButtonText : 'Submit';
$submitButtonClass = isset($submitButtonClass) ? $submitButtonClass : 'btn btn-primary';

?>

<?php if ($page->getFlashPosition() == FlashPositionCollection::POS_UP): ?>
    <?php $this->loadPartial('mf-flash'); ?>
<?php endif; ?>

<form action="<?= $action; ?>" autocomplete="<?= $page->getAutocomplete() ? 'on' : 'off'; ?>">
    <fieldset>
    <?php if (FieldService::hasColumns($fields)): ?>
        <div class="row">
            <?php foreach (FieldService::groupFields($fields) as $column => $collection): ?>
            <div data-column="<?= $column; ?>" class="<?= isset($classes[$column]) ? $classes[$column] : 'col-md-6'; ?>">
                <?php $this->loadPartial('mf-fields', [
                    'fields' => $collection
                ]); ?>
            </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <?php $this->loadPartial('mf-fields', [
            'fields' => $fields
        ]); ?>
    <?php endif; ?>

    <?php if ($page->getCaptcha()): ?>
    <div class="form-group row mb-3">
        <div class="col-lg-10 offset-lg-2">
            <a href="#" title="<?php $this->show('Click to refresh'); ?>" data-captcha="button-refresh" class="d-inline-block mb-2">
                <img data-captcha="image" src="<?php echo $this->url('Site:Main@captchaAction', null); ?>" class="img-fluid rounded" />
            </a>
            <?= Element::text('captcha', null, [
                'autocomplete' => 'off', 
                'class' => 'form-control', 
                'placeholder' => $this->translate('Enter what you see on image')
            ]); ?>
        </div>
    </div>
    <?php endif; ?>

    <?php if ($page->hasTerms()): ?>
    <div class="form-group mb-3">
        <div class="card card-body bg-light">
            <?= $page->getTerms(); ?>
        </div>
    </div>
    <?php endif; ?>

    <?php if (!empty($fields)): ?>
    <div class="form-group mt-4">
        <button type="submit" data-button="submit" class="<?= $submitButtonClass; ?>"><?php $this->show($submitButtonText); ?></button>
        <?php if ($resetButton): ?>
        <button type="reset" class="btn btn-secondary"><?php $this->show($resetButtonText); ?></button>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    </fieldset>
</form>

<?php if ($page->getFlashPosition() == FlashPositionCollection::POS_DOWN): ?>
    <?php $this->loadPartial('mf-flash'); ?>
<?php endif; ?>